/**
 * Client Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Client { 
    surname: string;
    firstName: string;
    middleName?: string;
    birthDate?: string;
    userId: number;
    username: string;
    bonuses: number;
}

