/**
 * Client Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Client } from './client';


export interface ClientsList { 
    items: Array<Client>;
    total: number;
}

