/**
 * Client Meal Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientMealIngredient } from './clientMealIngredient';


export interface ClientMeal { 
    mealId: number;
    amountInOrder: number;
    id: number;
    orderId: number;
    energeticValue: number;
    weight: number;
    price: number;
    ingredients: Array<ClientMealIngredient>;
}

