/**
 * Client Meal Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientMeal } from './clientMeal';


export interface ClientMealsList { 
    items: Array<ClientMeal>;
    total: number;
}

