/**
 * Client Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientsFilter { 
    page?: number;
    size?: number;
    sortBy?: string;
    descendingOrder?: boolean;
    query?: string;
    minBonuses?: number;
    maxBonuses?: number;
    minBirthDate?: string;
    maxBirthDate?: string;
}

