/**
 * Order Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateOrder { 
    restaurantId: number;
    employeeUserId?: number;
    clientUserId?: number;
    clientMeals: Array<{ [key: string]: any | undefined; }>;
}

