/**
 * Order Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientMealIngredient } from './clientMealIngredient';


export interface CreateClientMeal { 
    mealId: number;
    amountInOrder: number;
    ingredientOverrides?: Array<ClientMealIngredient>;
}

