/**
 * Employee Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeePosition } from './employeePosition';


export interface EmployeesFilter { 
    page?: number;
    size?: number;
    sortBy?: string;
    descendingOrder?: boolean;
    query?: string;
    minSalary?: number;
    maxSalary?: number;
    minBirthDate?: string;
    maxBirthDate?: string;
    positions?: Array<EmployeePosition>;
    managerUserId?: number;
    restaurantId?: number;
}

