/**
 * Employee Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeePosition } from './employeePosition';


export interface EmployeesStatisticFilter { 
    page?: number;
    size?: number;
    sortBy?: string;
    descendingOrder?: boolean;
    passportNumber?: string;
    position?: EmployeePosition;
    restaurantId?: number;
    minNumberOfOrders?: number;
    maxNumberOfOrders?: number;
    minTotalOrdersPrice?: number;
    maxTotalOrdersPrice?: number;
    fromDate?: string;
    toDate?: string;
}



