/**
 * Employee Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeePosition } from './employeePosition';


export interface EmployeeStatistic { 
    userId: number;
    passportNumber: string;
    surname: string;
    position: EmployeePosition;
    restaurantId?: number;
    restaurantAddress?: string;
    numberOfOrders: number;
    totalOrdersPrice: number;
}



