/**
 * Employee Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EmployeePosition = 'TOP_MANAGER' | 'MANAGER' | 'COOK' | 'CASHIER';

export const EmployeePosition = {

    TopManager: 'TOP_MANAGER' as EmployeePosition,

    Manager: 'MANAGER' as EmployeePosition,

    Cook: 'COOK' as EmployeePosition,

    Cashier: 'CASHIER' as EmployeePosition
};

