/**
 * Employee Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeeStatistic } from './employeeStatistic';


export interface EmployeesStatisticList { 
    items: Array<EmployeeStatistic>;
    total: number;
}

