/**
 * Employee Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum EmployeePosition {

    TOP_MANAGER = 'TOP_MANAGER',

    MANAGER = 'MANAGER',

    COOK = 'COOK',

    CASHIER = 'CASHIER'
}

