/**
 * Employee Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeePosition } from './employeePosition';


export interface EmployeeHiring { 
    passportNumber: string;
    surname: string;
    firstName: string;
    middleName?: string;
    salary: number;
    birthDate: string;
    username: string;
    password: string;
    position: EmployeePosition;
    managerUserId: number;
    restaurantId: number;
}



