/**
 * Image Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum ImageType {

    MEAL_IMAGE = 'MEAL_IMAGE',

    INGREDIENT_IMAGE = 'INGREDIENT_IMAGE'
}

