/**
 * Ingredient Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IngredientsInActiveUseFilter { 
    page?: number;
    size?: number;
    sortBy?: string;
    descendingOrder?: boolean;
    fromDate?: string;
    toDate?: string;
    isActual?: boolean;
}

