/**
 * Ingredient Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ingredient } from './ingredient';


export interface IngredientsList { 
    items: Array<Ingredient>;
    total: number;
}

