/**
 * Ingredient Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Ingredient { 
    energeticValue: number;
    weight: number;
    price: number;
    title: string;
    id: number;
}

