/**
 * Ingredient Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IngredientsFilter { 
    page?: number;
    size?: number;
    sortBy?: string;
    descendingOrder?: boolean;
    ids?: Array<number>;
    idsNot?: Array<number>;
    query?: string;
    minEnergeticValue?: number;
    maxEnergeticValue?: number;
    minWeight?: number;
    maxWeight?: number;
    minPrice?: number;
    maxPrice?: number;
    isActual?: boolean;
}

