/**
 * Meal Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MealStatistic { 
    id: number;
    title: string;
    clientMealsCount: number;
    lastOrderedDate?: string;
    isActual: boolean;
}

