/**
 * Meal Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Meal } from './meal';


export interface MealsList { 
    items: Array<Meal>;
    total: number;
}

