/**
 * Meal Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MealsStatisticFilter { 
    page?: number;
    size?: number;
    sortBy?: string;
    descendingOrder?: boolean;
    ids?: Array<number>;
    title?: string;
    minClientMealsCount?: number;
    maxClientMealsCount?: number;
    minLastOrderedDate?: string;
    maxLastOrderedDate?: string;
    isActual?: boolean;
}

