/**
 * Meal Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MealStatistic } from './mealStatistic';


export interface MealsStatisticList { 
    items: Array<MealStatistic>;
    total: number;
}

