/**
 * Meal Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MealIngredient } from './mealIngredient';


export interface Meal { 
    title: string;
    additionalPrice: number;
    description: string;
    recipe: string;
    ingredients: Array<MealIngredient>;
    id: number;
    energeticValue: number;
    weight: number;
    price: number;
}

