/**
 * Order Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Order { 
    restaurantId: number;
    employeeUserId?: number;
    clientUserId?: number;
    id: number;
    cost: number;
    dateCreated: string;
    isCompleted: boolean;
    clientMealsIds: Array<number>;
}

