/**
 * Order Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrdersFilter { 
    page?: number;
    size?: number;
    sortBy?: string;
    descendingOrder?: boolean;
    id?: number;
    restaurantId?: number;
    employeeUserId?: number;
    clientUserId?: number;
    minCost?: number;
    maxCost?: number;
    minDateCreated?: string;
    maxDateCreated?: string;
    isCompleted?: boolean;
}

