/**
 * Order Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Order { 
    restaurantId: number;
    employeeUserId?: number;
    clientUserId?: number;
    id: number;
    cost: number;
    restaurantAddress: string;
    employeeSurname?: string;
    clientSurname?: string;
    dateCreated: string;
    isCompleted: boolean;
}

