/**
 * Restaurant Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RestaurantsStatisticFilter { 
    page?: number;
    size?: number;
    sortBy?: string;
    descendingOrder?: boolean;
    address?: string;
    minNumberOfOrders?: number;
    maxNumberOfOrders?: number;
    minTotalOrdersPrice?: number;
    maxTotalOrdersPrice?: number;
    fromDate?: string;
    toDate?: string;
    hasManager?: boolean;
    isDeleted?: boolean;
}

