/**
 * Restaurant Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Restaurant } from './restaurant';


export interface RestaurantsList { 
    items: Array<Restaurant>;
    total: number;
}

