/**
 * Restaurant Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RestaurantStatistic } from './restaurantStatistic';


export interface RestaurantsStatisticList { 
    items: Array<RestaurantStatistic>;
    total: number;
}

