/**
 * Restaurant Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RestaurantStatistic { 
    address: string;
    id: number;
    managerUserId?: number;
    managerPassportNumber?: string;
    managerSurname?: string;
    numberOfOrders: number;
    totalOrdersPrice: number;
    isDeleted: boolean;
}

