/**
 * User Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRole = 'ADMIN' | 'CLIENT' | 'MANAGER' | 'COOK' | 'CASHIER';

export const UserRole = {

    Admin: 'ADMIN' as UserRole,

    Client: 'CLIENT' as UserRole,

    Manager: 'MANAGER' as UserRole,

    Cook: 'COOK' as UserRole,

    Cashier: 'CASHIER' as UserRole
};

