/**
 * User Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface User { 
    id: number;
    username: string;
    role: UserRole;
}
export namespace User {
}


