openapi: 3.0.0
info:
  title: Client Meal Service
  version: '1.0'
  description: Client Meal Service

tags:
  - name: client-meal-controller
    description: Client Meal Controller
servers:
  - url: http://localhost:8080

paths:
  /api/client-meal:
    get:
      operationId: getClientMealsByFilter
      tags:
        - client-meal-controller
      summary: Get client meals by filter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientMealsFilter'
      responses:
        200:
          description: List of client meals
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientMealsList'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

  /api/client-meal/{clientMealId}:
    parameters:
      - name: clientMealId
        in: path
        required: true
        schema:
          type: integer

    get:
      operationId: getClientMealById
      tags:
        - client-meal-controller
      summary: Get a client meal by its id
      responses:
        200:
          description: Client meal with corresponding id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientMeal'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

components:
  schemas:
    BaseClientMeal:
      type: object
      properties:
        mealId:
          type: integer
        amountInOrder:
          type: integer
      required:
        - mealId
        - amountInOrder

    CreateClientMeal:
      allOf:
        - $ref: '#/components/schemas/BaseClientMeal'
        - type: object
          properties:
            ingredientOverrides:
              type: array
              items:
                $ref: '#/components/schemas/ClientMealIngredient'

    ClientMeal:
      allOf:
        - $ref: '#/components/schemas/BaseClientMeal'
        - type: object
          properties:
            id:
              type: integer
            orderId:
              type: integer
            energeticValue:
              type: integer
            weight:
              type: integer
            price:
              type: number
            ingredients:
              type: array
              items:
                $ref: '#/components/schemas/ClientMealIngredient'
          required:
            - id
            - orderId
            - energeticValue
            - weight
            - price
            - ingredients

    ClientMealIngredient:
      type: object
      properties:
        ingredientId:
          type: integer
        amount:
          type: integer
      required:
        - ingredientId
        - amount

    ClientMealsList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ClientMeal'
        total:
          type: integer
          format: int64
      required:
        - items
        - total

    ClientMealsFilter:
      allOf:
        - $ref: 'common-types.yaml#/components/schemas/BaseFilter'
        - type: object
          properties:
            ids:
              type: array
              items:
                type: integer
            minEnergeticValue:
              type: integer
            maxEnergeticValue:
              type: integer
            minWeight:
              type: integer
            maxWeight:
              type: integer
            minPrice:
              type: number
            maxPrice:
              type: number
            orderId:
              type: integer
            mealId:
              type: integer
            minAmountInOrder:
              type: integer
            maxAmountInOrder:
              type: integer