openapi: 3.0.0
info:
  title: Ingredient Service
  version: '1.0'
  description: Ingredient Service

tags:
  - name: ingredient-controller
    description: Ingredient Controller

servers:
  - url: http://localhost:8080

paths:
  /api/ingredient:
    put:
      operationId: getIngredientsByFilter
      tags:
        - ingredient-controller
      summary: Get ingredients by filter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientsFilter'
      responses:
        200:
          description: List of ingredients
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientsList'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

    post:
      operationId: createIngredient
      tags:
        - ingredient-controller
      summary: Create new ingredient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIngredient'
      responses:
        200:
          description: Id of the created ingredient
          content:
            application/json:
              schema:
                type: integer
        400:
          $ref: 'common-types.yaml#/components/responses/BadRequest'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

  /api/ingredient/{ingredientId}:
    parameters:
      - name: ingredientId
        in: path
        required: true
        schema:
          type: integer

    get:
      operationId: getIngredientById
      tags:
        - ingredient-controller
      summary: Get ingredient by id
      parameters:
        - in: query
          name: requireActual
          required: false
          schema:
            type: boolean
            default: true
      responses:
        200:
          description: Ingredient with corresponding id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

    put:
      operationId: updateIngredient
      tags:
        - ingredient-controller
      summary: Update ingredient by id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateIngredient'
      responses:
        200:
          description: Id of the updated ingredient
          content:
            application/json:
              schema:
                type: integer
        400:
          $ref: 'common-types.yaml#/components/responses/BadRequest'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

    delete:
      operationId: deleteIngredient
      tags:
        - ingredient-controller
      summary: Delete ingredient by id
      responses:
        204:
          description: Ingredient deleted
        400:
          $ref: 'common-types.yaml#/components/responses/BadRequest'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

  /api/ingredient/valuable:
    put:
      operationId: getValuableIngredients
      tags:
        - ingredient-controller
      summary: Get valuable ingredients (ingredients that are used in every meal with price >= minMealPrice)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValuableIngredientsFilter'
      responses:
        200:
          description: List of valuable ingredients
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientsList'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

  /api/ingredient/in-active-use:
    put:
      operationId: getIngredientsInActiveUse
      tags:
        - ingredient-controller
      summary: Get ingredients in active use (ingredients that are used only in meals that have orders)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientsInActiveUseFilter'
      responses:
        200:
          description: List of ingredients in active use
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientsList'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

components:
  schemas:
    UpdateIngredient:
      type: object
      properties:
        energeticValue:
          type: integer
        weight:
          type: integer
        price:
          type: number
      required:
        - energeticValue
        - weight
        - price

    CreateIngredient:
      allOf:
        - $ref: '#/components/schemas/UpdateIngredient'
        - type: object
          properties:
            title:
              type: string
          required:
            - title

    Ingredient:
      allOf:
        - $ref: '#/components/schemas/CreateIngredient'
        - type: object
          properties:
            id:
              type: integer
          required:
            - id

    IngredientsList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        total:
          type: integer
          format: int64
      required:
        - items
        - total

    IngredientsFilter:
      allOf:
        - $ref: 'common-types.yaml#/components/schemas/BaseFilter'
        - type: object
          properties:
            ids:
              type: array
              items:
                type: integer
            idsNot:
              type: array
              items:
                type: integer
            query:
              type: string
            minEnergeticValue:
              type: integer
            maxEnergeticValue:
              type: integer
            minWeight:
              type: integer
            maxWeight:
              type: integer
            minPrice:
              type: number
            maxPrice:
              type: number
            isActual:
              type: boolean

    ValuableIngredientsFilter:
      allOf:
        - $ref: 'common-types.yaml#/components/schemas/BaseFilter'
        - type: object
          properties:
            minMealPrice:
              type: number
          required:
            - minMealPrice

    IngredientsInActiveUseFilter:
      allOf:
        - $ref: 'common-types.yaml#/components/schemas/BaseFilter'
        - type: object
          properties:
            fromDate:
              type: string
              format: date
            toDate:
              type: string
              format: date
            isActual:
              type: boolean