openapi: 3.0.0
info:
  title: Meal Service
  version: '1.0'
  description: Meal Service
tags:
  - name: meal-controller
    description: Meal Controller

servers:
  - url: http://localhost:8080

paths:
  /api/meal:
    put:
      operationId: getMealsByFilter
      tags:
        - meal-controller
      summary: Get meals by filter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MealsFilter'
      responses:
        200:
          description: List of meals
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MealsList'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

    post:
      operationId: createMeal
      tags:
        - meal-controller
      summary: Create a new meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMeal'
      responses:
        200:
          description: Id of the created meal
          content:
            application/json:
              schema:
                type: integer
        400:
          $ref: 'common-types.yaml#/components/responses/BadRequest'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

  /api/meal/{mealId}:
    parameters:
      - name: mealId
        in: path
        required: true
        schema:
          type: integer

    get:
      operationId: getMealById
      tags:
        - meal-controller
      summary: Get meal by id
      parameters:
        - in: query
          name: requireActual
          required: false
          schema:
            type: boolean
            default: true
      responses:
        200:
          description: Meal with corresponding id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

    put:
      operationId: updateMeal
      tags:
        - meal-controller
      summary: Update meal by id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMeal'
      responses:
        200:
          description: Id of the updated meal
          content:
            application/json:
              schema:
                type: integer
        400:
          $ref: 'common-types.yaml#/components/responses/BadRequest'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

    delete:
      operationId: deleteMeal
      tags:
        - meal-controller
      summary: Delete meal by id
      responses:
        204:
          description: Meal deleted
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

  /api/meal/statistic:
    put:
      operationId: getMealsStatisticByFilter
      tags:
        - meal-controller
      summary: Get meals statistic by filter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MealsStatisticFilter'
      responses:
        200:
          description: List of meals statistic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MealsStatisticList'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

components:
  schemas:
    UpdateMeal:
      type: object
      properties:
        additionalPrice:
          type: number
        description:
          type: string
        recipe:
          type: string
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/MealIngredient'
      required:
        - additionalPrice
        - description
        - recipe
        - ingredients

    MealIngredient:
      type: object
      properties:
        ingredientId:
          type: integer
        amount:
          type: integer
        isFixated:
          type: boolean
      required:
        - ingredientId
        - amount
        - isFixated

    CreateMeal:
      allOf:
        - $ref: '#/components/schemas/UpdateMeal'
        - type: object
          properties:
            title:
              type: string
          required:
            - title

    Meal:
      allOf:
        - $ref: '#/components/schemas/CreateMeal'
        - type: object
          properties:
            id:
              type: integer
            energeticValue:
              type: integer
            weight:
              type: integer
            price:
              type: number
          required:
            - id
            - energeticValue
            - weight
            - price

    MealsList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Meal'
        total:
          type: integer
          format: int64
      required:
        - items
        - total

    MealsFilter:
      allOf:
        - $ref: 'common-types.yaml#/components/schemas/BaseFilter'
        - type: object
          properties:
            ids:
              type: array
              items:
                type: integer
            idsNot:
              type: array
              items:
                type: integer
            query:
              type: string
            minEnergeticValue:
              type: integer
            maxEnergeticValue:
              type: integer
            minWeight:
              type: integer
            maxWeight:
              type: integer
            minPrice:
              type: number
            maxPrice:
              type: number
            minAdditionalPrice:
              type: number
            maxAdditionalPrice:
              type: number
            isActual:
              type: boolean

    MealStatistic:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        clientMealsCount:
          type: integer
        lastOrderedDate:
          type: string
          format: date-time
        isActual:
          type: boolean
      required:
        - id
        - title
        - clientMealsCount
        - isActual

    MealsStatisticList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/MealStatistic'
        total:
          type: integer
          format: int64
      required:
        - items
        - total

    MealsStatisticFilter:
      allOf:
        - $ref: 'common-types.yaml#/components/schemas/BaseFilter'
        - type: object
          properties:
            ids:
              type: array
              items:
                type: integer
            title:
              type: string
            minClientMealsCount:
              type: integer
            maxClientMealsCount:
              type: integer
            minLastOrderedDate:
              type: string
              format: date-time
            maxLastOrderedDate:
              type: string
              format: date-time
            isActual:
              type: boolean